# Generated by Django 4.0.5 on 2022-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_labs', '0003_alloptionpickerdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='experince_options',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='job_industry_option',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='job_skills_options',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='job_type_option',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='pay_types_options',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='working_day_options',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='alloptionpickerdata',
            name='working_hour_options',
            field=models.TextField(help_text='Options must be separated by comma with each other'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_industry',
            field=models.CharField(choices=[('Please choose an option', 'Please choose an option'), ('\r\nCorporate', '\r\nCorporate'), ('\r\nBank', '\r\nBank'), ('\r\nIT', '\r\nIT'), ('\r\nInformatics', '\r\nInformatics'), ('\r\nAutomobile', '\r\nAutomobile'), ('\r\nfreelance', '\r\nfreelance'), ('\r\nshare markets', '\r\nshare markets'), ('\r\nbiogenom', '\r\nbiogenom')], default='Choose an option', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_pay_rate_type',
            field=models.CharField(choices=[('Please choose an option', 'Please choose an option'), ('\r\nFreelancing', '\r\nFreelancing'), ('\r\nContactual', '\r\nContactual'), ('\r\nMonthly', '\r\nMonthly'), ('\r\nWeekly', '\r\nWeekly'), ('\r\nYearly', '\r\nYearly')], default='Choose an option', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_type',
            field=models.CharField(choices=[('Please choose an option', 'Please choose an option'), ('\r\nFreelancing', '\r\nFreelancing'), ('\r\nContactual', '\r\nContactual'), ('\r\nempolyee', '\r\nempolyee'), ('\r\nOthers', '\r\nOthers')], default='Choose an option', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='require_job_skill',
            field=models.CharField(choices=[('Please choose an option', 'Please choose an option'), ('\r\nUi designer', '\r\nUi designer'), ('\r\nPhotographer', '\r\nPhotographer'), ('\r\nGraphics Designer', '\r\nGraphics Designer'), ('\r\nDeveloper', '\r\nDeveloper'), ('\r\nDatabase Engineer', '\r\nDatabase Engineer')], default='Choose an option', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='required_job_experince',
            field=models.IntegerField(choices=[(1, '1 years'), (2, '\r\n2 years'), (3, '\r\n3 years'), (4, '\r\n4 years'), (5, '\r\n5 years'), (6, '\r\n6 years'), (7, '\r\n7 years'), (8, '\r\n8 years')], default='Choose an option'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='working_days',
            field=models.IntegerField(choices=[(1, '1'), (2, '\r\n2'), (3, '\r\n3'), (4, '\r\n4'), (5, '\r\n5'), (6, '\r\n6')], default='Choose an option'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='working_hours',
            field=models.IntegerField(choices=[(1, '1'), (2, '\r\n2'), (3, '\r\n3'), (4, '\r\n4'), (5, '\r\n5'), (6, '\r\n6'), (7, '\r\n7'), (8, '\r\n8')], default='Choose an option'),
        ),
    ]
